readable := {prototype: {}}
readwriteable := {base: readable, prototype: {base: readable.prototype}}
variables := define_vars()
define_vars() {
  r := {base: readable.prototype}
  rw := {base: readwriteable.prototype}
  return {
    AhkPath: A_ScriptFullPath,
    AhkVersion: JKVersion,
	AllowMainWindow: r,
	AppData: r,
	AppDataCommon: r,
	Clipboard: rw,
	ComputerName: r,
	ComSpec: r,
	ControlDelay: rw,
	CoordModeCaret: rw,
	CoordModeMenu: rw,
	CoordModeMouse: rw,
	CoordModePixel: rw,
	CoordModeToolTip: rw,
	Cursor: r,
	DD: r,
	DDD: r,
	DDDD: r,
	DefaultMouseSpeed: rw,
	Desktop: r,
	DesktopCommon: r,
	DetectHiddenText: rw,
	DetectHiddenWindows: rw,
	EndChar: r,
	EventInfo: rw,
	FileEncoding: rw,
	Hour: r,
	IconFile: r,
	IconHidden: {get: GetIconHidden, set: SetIconHidden},
	IconNumber: r,
	IconTip: rw,
	InitialWorkingDir: A_InitialWorkingDir,
	Is64bitOS: ComObject(0xB, -A_Is64bitOS),
	IsAdmin: ComObject(0xB, -A_IsAdmin),
    IsCompiled: ComObject(0xB, 0),
	; IsCritical: r,
    IsPaused: {get: () => ComObject(0xB, -A_IsPaused)},
    IsSuspended: {get: () => ComObject(0xB, -A_IsSuspended)},
	KeyDelay: rw,
	KeyDelayPlay: rw,
	KeyDuration: rw,
	KeyDurationPlay: rw,
	Language: r,
	LastError: rw,
	LineFile: {get: GetLineFile},
	LineNumber: {get: GetLineNumber},
	ListLines: rw,
	; LoopField: r,
	; LoopFileAttrib: r,
	; LoopFileDir: r,
	; LoopFileExt: r,
	; LoopFileFullPath: r,
	; LoopFileName: r,
	; LoopFilePath: r,
	; LoopFileShortName: r,
	; LoopFileShortPath: r,
	; LoopFileSize: r,
	; LoopFileSizeKB: r,
	; LoopFileSizeMB: r,
	; LoopFileTimeAccessed: r,
	; LoopFileTimeCreated: r,
	; LoopFileTimeModified: r,
	; LoopReadLine: r,
	; LoopRegKey: r,
	; LoopRegName: r,
	; LoopRegTimeModified: r,
	; LoopRegType: r,
	MDay: r,
	Min: r,
	MM: r,
	MMM: r,
	MMMM: r,
	Mon: r,
	MouseDelay: rw,
	MouseDelayPlay: rw,
	MSec: r,
	MyDocuments: r,
	Now: r,
	NowUTC: r,
	OSVersion: A_OSVersion,
	PriorHotkey: r,
	PriorKey: r,
	ProgramFiles: r,
	Programs: r,
	ProgramsCommon: r,
	PtrSize: A_PtrSize,
	RegView: rw,
	ScreenDPI: r,
	ScreenHeight: r,
	ScreenWidth: r,
    ScriptDir: J_ScriptDir,
    ScriptFullPath: J_ScriptFullPath,
	ScriptHwnd: A_ScriptHwnd,
	ScriptName: rw,
	Sec: r,
	SendLevel: rw,
	SendMode: rw,
	; Space: r,
	StartMenu: r,
	StartMenuCommon: r,
	Startup: r,
	StartupCommon: r,
	StoreCapsLockMode: rw,
	; Tab: r,
	Temp: r,
	; ThisFunc: r,
	ThisHotkey: r,
	TickCount: r,
	TimeIdle: r,
	TimeIdleKeyboard: r,
	TimeIdleMouse: r,
	TimeIdlePhysical: r,
	TimeSincePriorHotkey: r,
	TimeSinceThisHotkey: r,
	TitleMatchMode: rw,
	TitleMatchModeSpeed: rw,
	TrayMenu: r,
	UserName: r,
	WDay: r,
	WinDelay: rw,
	WinDir: r,
	WorkingDir: rw,
	YDay: r,
	Year: r,
	YWeek: r,
	YYYY: r,
  }
}